# Day 8 ML/RL Prep

5 basic mixed questions. Today revisits masked means and keeps shape/debugging practice light.

Instructions:
- Answer with reasoning, not just the final result.
- Keep explanations short and precise.
- If you write code, explain what each dimension means.


## Question 1: Scalar masked mean

You have:
- `x`: shape `(B, T) = (2, 3)`
- `mask`: shape `(B, T) = (2, 3)` with 0/1 values

You want one scalar: the mean of all valid entries in `x`.

What should the numerator be?
What should the denominator be?
Why should the denominator come from `mask`, not from `(x * mask) != 0`?


In [13]:
# Question 1: Answer and reasoning
import torch

x = torch.randn(2, 3)
mask = torch.randint(0, 2, (2, 3))

masked_x = mask*x
mask_count = mask.sum().item()

avg = masked_x.sum() / mask_count
avg = (masked_x.sum().item() / mask_count)
avg

# The numerator should be the sum of x*mask.
# The denominator needs to then be sum of the mask which will corrispond with the number of non-zero entries in the mask as their values can only be 0 or 1. 
# The denominator should not be (x * mask) != 0 because there may be 0 values in the input tensor, x.

-0.785617470741272

## Question 2: Per-feature masked mean

You have:
- `x`: shape `(B, T, D) = (2, 3, 5)`
- `mask`: shape `(B, T) = (2, 3)` with 0/1 values

You want the mean valid feature vector over batch and time.

What shape should the output have?
What shape should `mask` have before multiplying `x`?
Which dimensions should the numerator sum over?
What should the denominator count?


## Question 3: `gather` with `(B, T, A)`

You have:
- `logits`: shape `(B, T, A) = (2, 3, 4)`
- `actions`: shape `(B, T) = (2, 3)`

You want one chosen-action logit for each `(batch, time)` position.

What shape should `actions` have after `unsqueeze` before `gather`?
What dimension should you gather over?
What shape is the result before and after squeezing?


In [64]:
# Question 3: Answer and reasoning

b, t, a = 2, 3, 4
logits = torch.randn(b, t, a)
actions = torch.randint(0, a, (b, t))

scores = torch.gather(logits, 2, actions.unsqueeze(-1)).squeeze(-1)
logits, actions, scores

# After unsqueeze actions should have the shape (b, t, 1) as we add a trailing dimention. 
# We should gather over the third dimention (actions) (index=2).
# the result will be of shape (b, t, 1), before squeezing.
# The result will be of shape (b, t) after squeezing.

(tensor([[[-0.0853,  0.9590, -0.5321, -0.1955],
          [ 0.2945, -1.9423, -0.2587, -0.0887],
          [-0.9282, -0.3932, -0.5627, -0.0871]],
 
         [[ 1.5069, -0.6948,  0.1968,  0.7844],
          [-0.7198,  1.8598, -0.3116,  0.0363],
          [-0.6307,  0.8995,  1.0653, -0.2079]]]),
 tensor([[1, 3, 1],
         [0, 0, 2]]),
 tensor([[ 0.9590, -0.0887, -0.3932],
         [ 1.5069, -0.7198,  1.0653]]))

## Question 4: Debugging `cross_entropy` target shape

Consider:

```python
logits = torch.randn(6, 4)
target = torch.randint(0, 4, (6, 1))
loss = F.cross_entropy(logits, target)
```

What is wrong with `target`?
What shape should it have?
Why?


In [ ]:
# Question 4: Answer and reasoning


# Torch's cross entropy method requires the inputs (logits) to be shape (N, C)
# And the targets to be of shape (N,).
# The target has shape (6, 1). 
# It needs to have the shape (6,) for the reason just mentioned. 
# This could be accomplished with squeeze(-1) to remove the trailing dimention.

## Question 5: Reading shapes after flattening

You have:
- `obs`: shape `(B, T, D) = (2, 4, 3)`
- `actions`: shape `(B, T) = (2, 4)`

You flatten them as:

```python
obs_flat = obs.reshape(-1, D)
actions_flat = actions.reshape(-1)
```

What are the two shapes?
What does row `i` of `obs_flat` correspond to conceptually?
What does element `i` of `actions_flat` correspond to?


In [75]:
# Question 5: Answer and reasoning

b, t, d = 2, 4, 3
obs = torch.randn(b, t, d)
actions = torch.randint(0, 5, (b, t))

obs_flat = obs.reshape(-1, d)
actions_flat = actions.reshape(-1)
obs_flat.shape, actions_flat.shape

# obs_flat is of shape (8, 3) and actions_flat is shape (8,)
# i'th row of obs_flat is the i'th batch-time sample of the observation.
# The i'th row of the actions_flat is xthe action taken at that i'th batch-time sample.

(torch.Size([8, 3]), torch.Size([8]), torch.Size([2, 4]))